############################# English ############################
[en]
languageName = "English ðŸ‡¬ðŸ‡§"
title = "PPME Demo Website 001"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "PPME Den Haag"
footer_menu_middle = "Activities"
footer_menu_right = "Services"
footer_content = "Yes, we can make (relatively) beautiful website without WordPress"
# copyright
copyright = "PPME Den Haag IT Division 2022, based on [Bigspring-Light](https://github.com/themefisher/bigspring-light) Hugo Design"



############################# Netherlands ############################
[nl]
languageName = "Nederland ðŸ‡³ðŸ‡±"
title = "PPME Demo Website 001"
contentDir = "content/nl" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "PPME Den Haag"
footer_menu_middle = "Activities"
footer_menu_right = "Services"
footer_content = "Ja, we kunnen een prachtige website maken zonder WordPress"
# copyright
copyright = "PPME Den Haag IT Division 2022, gebaseerd op [Bigspring-Light](https://github.com/themefisher/bigspring-light) Hugo Design"