# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

##[[main]]
##name = "Blog"
##url = "blog/"
##weight = 2

[[main]]
name = "Dakwah"
weight = 3

[[main]]
parent = "Dakwah"
name = "Al Moeminoen"
weight = 3


[[main]]
parent = "Dakwah"
name = "Qur'anlessen"
weight = 3


[[main]]
parent = "Dakwah"
name = "Indonesische Bijeenkomst"
weight = 3

[[main]]
name = "Ibadah"
weight = 3

[[main]]
name = "Islamiitisch Trouwen"
parent = "Ibadah"
url = "ibadah/marriage/"
weight = 3

[[main]]
name = "Geboorte"
parent = "Ibadah"
url = "birth/"
weight = 3

[[main]]
name = "Toetreden tot de Islam"
parent = "Ibadah"
url = "joining-Islam/"
weight = 3

[[main]]
name = "Overlijden"
parent = "Ibadah"
url = "passing-away/"
weight = 3

[[main]]
name = "Zakat, Infaq en Sadaqah"
parent = "Ibadah"
url = "zakat-infaq-shodaqoh/"
weight = 3



##[[main]]
##name = "Pricing"
##url = "pricing/"
##weight = 3


[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]
name = "Pricing"
url = "pricing/"


# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing/"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"

[[footer_right]]
name = "FAQ"
url = "faq/"